### ISSUE TITLE
Questions about dataset documentation - Is it possible to provide dataset download command

### ISSUE THREAD

**Issue by WILLOSCAR** [facebookresearch/imu2clip#3]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [x] Documentation Ask

## Description
Hello, I would like to ask some questions about dataset documentation. In imu2clip/datasets/ego4d/README.md, which is the specific video dataset that was downloaded. Based on my current hardware, it's very difficult to download the full video dataset using the command(python3 -m ego4d.cli.cli --output_directory="~/ego4d_data" --dataset=clips), so I wanted to reduce the download size. If so, is it possible to provide the full dataset download command(imu and video).

## Current Behavior
I have downloaded the imu dataset using this command(python3 -m ego4d.cli.cli --output_directory="~/ego4d_data" --dataset=clips)
I'm confused is this correct?
## Expected Behavior
Can you provide the full download command for the ego4d dataset used in this github (including imu and video)?

**Comment by andreamad8** [comment]
Hi there, 

I haven't download the dataset myself, cause we have it already store internally. 

I think the right way it's to download the dataset via the CLI provided by ego4d. In general I used the full_scale video in this case, because the narration were timestamp with that respect. 

-- Andrea
