### ISSUE TITLE
Update the hardcoded data paths

### ISSUE THREAD

**Issue by pranay-ar** [facebookresearch/imu2clip#5]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [x] Refactor request
- [ ] Documentation Ask

## Description

Currently, most of the datapaths in the [preprocessing](https://github.com/facebookresearch/imu2clip/blob/b00548fb4bf0923db2a443466b8b36b81fcf72bb/dataset/ego4d/preprocessing_scripts/preprocess.sh#L10) and [utils](https://github.com/facebookresearch/imu2clip/blob/b00548fb4bf0923db2a443466b8b36b81fcf72bb/dataset/ego4d/utils/utils.py#L23) scripts are hardcoded and I was curious to know if I could contribute to this issue by updating and cleaning up the hardcoded data paths.

**Comment by andreamad8** [comment]
pls open a pull request for this. 
--Andrea
